"""Add further attributes to venue  model

Revision ID: 46fc3ca4a5e6
Revises: f04c000aa187
Create Date: 2022-12-03 09:57:40.435445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fc3ca4a5e6'
down_revision = 'f04c000aa187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_currently_seeking_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quote_talent_seeking', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('quote_talent_seeking')
        batch_op.drop_column('is_currently_seeking_talent')
        batch_op.drop_column('website_link')
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
