"""Avoid property name collision in sql alchemy models

Revision ID: c48dddd51519
Revises: 46fc3ca4a5e6
Create Date: 2022-12-03 11:07:34.073047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48dddd51519'
down_revision = '46fc3ca4a5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('show_artist_fkey', type_='foreignkey')
        batch_op.drop_constraint('show_venue_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.drop_column('venue')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('show_venue_fkey', 'Venue', ['venue'], ['id'])
        batch_op.create_foreign_key('show_artist_fkey', 'Artist', ['artist'], ['id'])
        batch_op.drop_column('venue_id')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
