"""Add further attributes to artist model

Revision ID: f04c000aa187
Revises: 016cb9e9cf21
Create Date: 2022-12-03 09:51:21.976870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04c000aa187'
down_revision = '016cb9e9cf21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_currently_seeking_performance_venues', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quote_venue_seeking', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('quote_venue_seeking')
        batch_op.drop_column('is_currently_seeking_performance_venues')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
